parking_app/routes.py
from datetime import datetime
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_user, logout_user, login_required, current_user

from .models import (
    db,
    User,
    PropertyCustomer,
    ParkingCustomer,
    SecurityCustomer,
    SecurityProperty,
    Credential,
)
from . import login_manager

bp = Blueprint('main', __name__)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


@bp.route('/')
def index():
    properties = PropertyCustomer.query.all()
    return render_template('index.html', properties=properties)


@bp.route('/register_vehicle', methods=['GET', 'POST'])
def register_vehicle():
    if request.method == 'POST':
        prop_id = request.form.get('property_id')
        first = request.form.get('first_name')
        last = request.form.get('last_name')
        unit = request.form.get('unit')
        plate = request.form.get('license_plate')
        departure = datetime.strptime(request.form['departure_date'], '%Y-%m-%d')

        customer = ParkingCustomer(
            Property_ID=prop_id,
            First_Name=first,
            Last_Name=last,
            Unit=unit,
            License_Plate=plate,
            Departure_Date=departure,
        )
        db.session.add(customer)
        db.session.commit()
        return redirect(url_for('main.index'))

    properties = PropertyCustomer.query.all()
    return render_template('register_vehicle.html', properties=properties)


@bp.route('/signup/property', methods=['GET', 'POST'])
def signup_property():
    if request.method == 'POST':
        name = request.form['property_name']
        address = request.form['property_address']
        city = request.form['property_city']
        state = request.form['property_state']
        zip_code = request.form['property_zip']
        contact = request.form['contact_number']
        username = request.form['username']
        password = request.form['password']

        prop = PropertyCustomer(
            Property_Name=name,
            Property_Address=address,
            Property_City=city,
            Property_State=state,
            Property_Zip=zip_code,
            Contact_Number=contact,
        )
        db.session.add(prop)
        db.session.flush()

        user = User(Role='property_owner', Property_ID=prop.Property_ID)
        db.session.add(user)
        db.session.flush()

        cred = Credential(User_ID=user.User_ID, Username=username)
        cred.set_password(password)
        db.session.add(cred)
        db.session.commit()

        login_user(user)
        return redirect(url_for('main.owner_dashboard'))

    return render_template('signup_property.html')


@bp.route('/signup/security', methods=['GET', 'POST'])
def signup_security():
    if request.method == 'POST':
        name = request.form['security_name']
        address = request.form['security_address']
        city = request.form['security_city']
        state = request.form['security_state']
        zip_code = request.form['security_zip']
        username = request.form['username']
        password = request.form['password']

        sec = SecurityCustomer(
            Security_Name=name,
            Security_Address=address,
            Security_City=city,
            Security_State=state,
            Security_Zip=zip_code,
        )
        db.session.add(sec)
        db.session.flush()

        user = User(Role='security_admin', Security_ID=sec.Security_ID)
        db.session.add(user)
        db.session.flush()

        cred = Credential(User_ID=user.User_ID, Username=username)
        cred.set_password(password)
        db.session.add(cred)
        db.session.commit()

        login_user(user)
        return redirect(url_for('main.security_dashboard'))

    return render_template('signup_security.html')


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        cred = Credential.query.filter_by(Username=username, Current_Flag=True).first()
        if cred and cred.check_password(password):
            login_user(cred.user)
            if cred.user.Role == 'property_owner':
                return redirect(url_for('main.owner_dashboard'))
            if cred.user.Role in ['security_admin', 'security_guard']:
                return redirect(url_for('main.security_dashboard'))
            return redirect(url_for('main.index'))
    return render_template('login.html')


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@bp.route('/owner_dashboard', methods=['GET', 'POST'])
@login_required
def owner_dashboard():
    if current_user.Role != 'property_owner':
        return redirect(url_for('main.index'))

    property_obj = current_user.property
    security_companies = SecurityCustomer.query.all()
    assigned = SecurityProperty.query.filter_by(
        Property_ID=property_obj.Property_ID, Current_Flag=True
    ).all()

    if request.method == 'POST':
        security_id = request.form.get('security_id')
        if security_id:
            existing = SecurityProperty.query.filter_by(
                Property_ID=property_obj.Property_ID,
                Security_ID=security_id,
                Current_Flag=True,
            ).first()
            if not existing:
                link = SecurityProperty(
                    Property_ID=property_obj.Property_ID, Security_ID=security_id
                )
                db.session.add(link)
                db.session.commit()
            return redirect(url_for('main.owner_dashboard'))

    reg_count = ParkingCustomer.query.filter_by(
        Property_ID=property_obj.Property_ID
    ).count()

    return render_template(
        'owner_dashboard.html',
        property=property_obj,
        security_companies=security_companies,
        assigned=assigned,
        registered_count=reg_count,
    )


@bp.route('/security_dashboard', methods=['GET', 'POST'])
@login_required
def security_dashboard():
    if current_user.Role not in ['security_admin', 'security_guard']:
        return redirect(url_for('main.index'))

    security_obj = current_user.security
    properties = [
        link.property for link in security_obj.properties if link.Current_Flag
    ]
    employees = User.query.filter_by(
        Security_ID=security_obj.Security_ID, Current_Flag=True
    ).all()

    if request.method == 'POST' and current_user.Role == 'security_admin':
        first = request.form['first_name']
        last = request.form['last_name']
        role = request.form['role']
        username = request.form['username']
        password = request.form['password']

        new_user = User(
            First_Name=first,
            Last_Name=last,
            Role=role,
            Security_ID=security_obj.Security_ID,
        )
        db.session.add(new_user)
        db.session.flush()

        cred = Credential(User_ID=new_user.User_ID, Username=username)
        cred.set_password(password)
        db.session.add(cred)
        db.session.commit()
        return redirect(url_for('main.security_dashboard'))

    return render_template(
        'security_dashboard.html',
        security=security_obj,
        properties=properties,
        employees=employees,
    )


@bp.route('/remove_employee/<int:user_id>', methods=['POST'])
@login_required
def remove_employee(user_id):
    if current_user.Role != 'security_admin':
        return redirect(url_for('main.security_dashboard'))

    user = User.query.filter_by(
        User_ID=user_id,
        Security_ID=current_user.Security_ID,
        Current_Flag=True,
    ).first()
    if user:
        user.Current_Flag = False
        if user.credentials:
            user.credentials.Current_Flag = False
        db.session.commit()
    return redirect(url_for('main.security_dashboard'))

parking_app/templates/base.html
<!doctype html>
<title>Parking Monitor</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{{ url_for('main.index') }}">Parking Monitor</a>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><a class="nav-link" href="{{ url_for('main.register_vehicle') }}">Register Vehicle</a></li>
      {% if current_user.is_authenticated and current_user.Role == 'property_owner' %}
      <li class="nav-item"><a class="nav-link" href="{{ url_for('main.owner_dashboard') }}">Dashboard</a></li>
      {% endif %}
    </ul>
    {% if current_user.is_authenticated %}
      <a class="btn btn-outline-danger" href="{{ url_for('main.logout') }}">Logout</a>
    {% else %}
      <a class="btn btn-outline-secondary me-2" href="{{ url_for('main.signup_property') }}">Property Sign Up</a>
      <a class="btn btn-outline-secondary me-2" href="{{ url_for('main.signup_security') }}">Security Sign Up</a>
      <a class="btn btn-outline-primary" href="{{ url_for('main.login') }}">Login</a>
    {% endif %}
  </div>
</nav>
<div class="container mt-4">
  {% block content %}{% endblock %}
</div>

parking_app/templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Properties</h1>
<ul>
  {% for prop in properties %}
    <li>{{ prop.Property_Name }} - {{ prop.Property_Address }}</li>
  {% endfor %}
</ul>
{% endblock %}

parking_app/templates/login.html
{% extends 'base.html' %}
{% block content %}
<h2>Login</h2>
<form method="post">
  <div class="mb-3">
    <label class="form-label">Username</label>
    <input class="form-control" type="text" name="username">
  </div>
  <div class="mb-3">
    <label class="form-label">Password</label>
    <input class="form-control" type="password" name="password">
  </div>
  <button class="btn btn-primary" type="submit">Login</button>
</form>
{% endblock %}

parking_app/templates/owner_dashboard.html
{% extends 'base.html' %}
{% block content %}
<h2>{{ property.Property_Name }} Dashboard</h2>
<p>Registered vehicles: {{ registered_count }}</p>
<h4>Assign Security Company</h4>
<form method="post" class="mb-3">
  <div class="input-group">
    <select name="security_id" class="form-select">
      {% for sec in security_companies %}
      <option value="{{ sec.Security_ID }}">{{ sec.Security_Name }}</option>
      {% endfor %}
    </select>
    <button class="btn btn-primary" type="submit">Assign</button>
  </div>
</form>
<h4>Current Security Companies</h4>
<ul>
  {% for link in assigned %}
  <li>{{ link.security.Security_Name }}</li>
  {% else %}
  <li>No security company assigned</li>
  {% endfor %}
</ul>
{% endblock %}

parking_app/templates/register_vehicle.html
{% extends 'base.html' %}
{% block content %}
<h2>Register Vehicle</h2>
<form method="post">
  <div class="mb-3">
    <label class="form-label">First Name</label>
    <input class="form-control" name="first_name">
  </div>
  <div class="mb-3">
    <label class="form-label">Last Name</label>
    <input class="form-control" name="last_name">
  </div>
  <div class="mb-3">
    <label class="form-label">Unit / Apartment</label>
    <input class="form-control" name="unit">
  </div>
  <div class="mb-3">
    <label class="form-label">License Plate</label>
    <input class="form-control" name="license_plate">
  </div>
  <div class="mb-3">
    <label class="form-label">Departure Date</label>
    <input class="form-control" type="date" name="departure_date">
  </div>
  <div class="mb-3">
    <label class="form-label">Property</label>
    <select class="form-select" name="property_id">
      {% for prop in properties %}
        <option value="{{ prop.Property_ID }}">{{ prop.Property_Name }}</option>
      {% endfor %}
    </select>
  </div>
  <button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

parking_app/templates/security_dashboard.html
{% extends 'base.html' %}
{% block content %}
<h2>Security Dashboard</h2>
<h3>Properties</h3>
<ul>
  {% for prop in properties %}
  <li>{{ prop.Property_Name }}</li>
  {% else %}
  <li>No properties assigned.</li>
  {% endfor %}
</ul>

{% if current_user.Role == 'security_admin' %}
<h3>Add Employee</h3>
<form method="post">
  <div class="mb-3">
    <input class="form-control" name="first_name" placeholder="First Name" required>
  </div>
  <div class="mb-3">
    <input class="form-control" name="last_name" placeholder="Last Name" required>
  </div>
  <div class="mb-3">
    <select class="form-select" name="role" required>
      <option value="security_admin">Admin</option>
      <option value="security_guard">Security Guard</option>
    </select>
  </div>
  <div class="mb-3">
    <input class="form-control" name="username" placeholder="Username" required>
  </div>
  <div class="mb-3">
    <input class="form-control" type="password" name="password" placeholder="Password" required>
  </div>
  <button class="btn btn-primary" type="submit">Add User</button>
</form>

<h3>Employees</h3>
<ul>
  {% for emp in employees %}
  <li>{{ emp.First_Name }} {{ emp.Last_Name }} ({{ emp.Role }})
    {% if emp.User_ID != current_user.User_ID %}
    <form method="post" action="{{ url_for('main.remove_employee', user_id=emp.User_ID) }}" style="display:inline">
      <button class="btn btn-sm btn-danger" type="submit">Remove</button>
    </form>
    {% endif %}
  </li>
  {% else %}
  <li>No employees.</li>
  {% endfor %}
</ul>
{% endif %}
{% endblock %}

parking_app/templates/signup_property.html
{% extends 'base.html' %}
{% block content %}
<h2>Property Owner Sign Up</h2>
<form method="post">
  <div class="mb-3">
    <input class="form-control" name="property_name" placeholder="Property Name" required>
  </div>
  <div class="mb-3">
    <input class="form-control" name="property_address" placeholder="Address" required>
  </div>
  <div class="mb-3">
    <input class="form-control" name="property_city" placeholder="City" required>
  </div>
  <div class="mb-3">
    <input class="form-control" name="property_state" placeholder="State" maxlength="2" required>
  </div>
  <div class="mb-3">
    <input class="form-control" name="property_zip" placeholder="Zip" required>
  </div>
  <div class="mb-3">
    <input class="form-control" name="contact_number" placeholder="Contact Number" required>
  </div>
  <div class="mb-3">
    <input class="form-control" name="username" placeholder="Username" required>
  </div>
  <div class="mb-3">
    <input class="form-control" type="password" name="password" placeholder="Password" required>
  </div>
  <button class="btn btn-primary" type="submit">Sign Up</button>
</form>
{% endblock %}

parking_app/templates/signup_security.html
{% extends 'base.html' %}
{% block content %}
<h2>Security Company Sign Up</h2>
<form method="post">
  <div class="mb-3">
    <input class="form-control" name="security_name" placeholder="Company Name" required>
  </div>
  <div class="mb-3">
    <input class="form-control" name="security_address" placeholder="Address" required>
  </div>
  <div class="mb-3">
    <input class="form-control" name="security_city" placeholder="City" required>
  </div>
  <div class="mb-3">
    <input class="form-control" name="security_state" placeholder="State" maxlength="2" required>
  </div>
  <div class="mb-3">
    <input class="form-control" name="security_zip" placeholder="Zip" required>
  </div>
  <div class="mb-3">
    <input class="form-control" name="username" placeholder="Username" required>
  </div>
  <div class="mb-3">
    <input class="form-control" type="password" name="password" placeholder="Password" required>
  </div>
  <button class="btn btn-primary" type="submit">Sign Up</button>
</form>
{% endblock %}